# Generated by Django 5.0.4 on 2024-04-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moleculeslist',
            name='molecular_weight',
            field=models.TextField(default=10),
            preserve_default=False,
        ),
    ]
